# file      : tests/basic/buildfile
# license   : GPLv2 with Universal FOSS Exception; see accompanying LICENSE file

import libs = libmysqlclient%lib{mysqlclient}

exe{driver}: {h c}{*} $libs testscript
